theme: jekyll-theme-minimal
title: Metamine Ontology (MO) for Discovery of Advanced Metamaterials
description: <p align="justify">Neha Keshan, James P. McCusker, Michael Deagen, and Deborah L. McGuinness</p><p>A resource website for the 2020 ISWC Resource Track Submission </p>